name: Daily Build Release

on:
  schedule:
    # This is a UTC time
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  push-images:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3

      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "zhangliang-s3-test"
        run: |
          bash scripts/image-manifest.sh

  push-deps:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3

      # test
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "zhangliang-s3-test"
        run: |
          bash scripts/deps-manifest.sh

  upload-package:
    needs: [push-images, push-deps]
    runs-on: ubuntu-latest

    steps:
      - name: "Daily tag version"
        id: vars
        run: |
          v=1.11.0-$(date +"%Y%m%d")
          echo "tag_version=$v" >> $GITHUB_OUTPUT

      - name: "Checkout source code"
        uses: actions/checkout@v3

      - name: Package installer
        run: |
          bash scripts/build.sh ${{ steps.vars.outputs.tag_version }}

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "zhangliang-s3-test"
        run: |
          md5sum install-wizard-v${{ steps.vars.outputs.tag_version }}.tar.gz > install-wizard-v${{ steps.vars.outputs.tag_version }}.md5sum.txt && \
          aws s3 cp install-wizard-v${{ steps.vars.outputs.tag_version }}.md5sum.txt s3://zhangliang-s3-test/test2/install-wizard-v${{ steps.vars.outputs.tag_version }}.md5sum.txt --acl=public-read && \
          aws s3 cp install-wizard-v${{ steps.vars.outputs.tag_version }}.tar.gz s3://zhangliang-s3-test/test2/install-wizard-v${{ steps.vars.outputs.tag_version }}.tar.gz --acl=public-read

  release:
    needs: [upload-package]
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3

      - name: "Daily tag version"
        id: vars
        run: |
          v=1.11.0-$(date +"%Y%m%d")
          echo "tag_version=$v" >> $GITHUB_OUTPUT

      - name: Update checksum
        uses: eball/write-tag-to-version-file@latest
        with:
          filename: "build/installer/install.sh"
          placeholder: "#__MD5SUM__"
          tag: ${{ steps.vars.outputs.version_md5sum }}

      - name: Package installer
        run: |
          bash scripts/build.sh ${{ steps.vars.outputs.tag_version }}

      - name: "Archives"
        run: |
          cp .dist/install-wizard/install.sh build/installer
          cp build/installer/install.sh build/installer/publicInstaller.sh
          cp .dist/install-wizard/install.ps1 build/installer

      - name: Release public files
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.vars.outputs.tag_version }} Release
          tag_name: ${{ steps.vars.outputs.tag_version }}
          files: |
            install-wizard-v${{ steps.vars.outputs.tag_version }}.tar.gz
            build/installer/publicInstaller.sh
            build/installer/install.sh
            build/installer/install.ps1
            build/installer/publicAddnode.sh
            build/installer/version.hint
            build/installer/publicRestoreInstaller.sh
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
