name: Windows Test

on:
  workflow_dispatch:

jobs:
  signing: # todo 签名
    runs-on: windows-latest
    steps:
      - name: "Start"
        run: |
          pwd

      - name: "Start1"
        run: |
          Get-ChildItem -Path .

      - name: "Signing"
        run: |
          systeminfo ;  Write-Host "" ; $PSVersionTable.PSVersion ; Write-Host "" ; Get-ChildItem -Path Cert:\CurrentUser\My

      # - name: "Sign"
      #   run: |

      - name: "Policy"
        run: |
          Get-ExecutionPolicy -List
