name: Windows Test

on:
  workflow_dispatch:

jobs:
  signing: # todo 签名
    runs-on: windows-latest
    steps:
      - name: "Signing"
        run: |
          systeminfo ;  Write-Host "" ; $PSVersionTable.PSVersion ;  Write-Host "---line---" ; Get-ExecutionPolicy -List
