name: Windows Test

on:
  workflow_dispatch:

jobs:
  signing: # todo 签名
    runs-on: windows-latest
    steps:
      - name: "Start"
        run: |
          pwd

      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          ref: refs/heads/main

      - name: "Show"
        run: |
          gci

      - name: "Copy Files"
        run: |
          Copy-Item -Path .\build\installer\install.ps1 -Destination . ; Copy-Item -Path .\scripts\create-cert.ps1 -Destination .

      - name: "Show"
        run: |
          gci

      - name: "Policy"
        run: |
          Get-ExecutionPolicy -List

      # - name: "Run Create Cert"
      #   run: |
      #     .\create-cert.ps1

      - name: "Go1"
        run: |
          cd /; gci
        continue-on-error: true

      - name: "Go2"
        run: |
          c:; cd /; cd '.\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64'; gci
        continue-on-error: true
