name: Windows Test

on:
  workflow_dispatch:

jobs:
  signing: # todo 签名
    runs-on: windows-latest
    steps:
      - name: "Start"
        run: |
          pwd

      - name: "Check PowerShell Version"
        run: |
          $PSVersionTable.PSVersion

      - name: "Get"
        run: |
          Write-Host "---get---" ; cd .. ; gci

      - name: "Get1"
        run: |
          Write-Host "---get1---" ; cd .. ; cd .. ; gci

      - name: "Get2"
        run: |
          Write-Host "---get2---" ; cd .. ; cd .. ; cd .. ; gci

      - name: "Line"
        run: |
          Write-Host "---line---"

      - name: "Signing"
        run: |
          systeminfo ;  Write-Host "" ; $PSVersionTable.PSVersion ; Write-Host "" ; Get-ChildItem -Path Cert:\CurrentUser\My

      # - name: "Sign"
      #   run: |

      - name: "Policy"
        run: |
          Get-ExecutionPolicy -List
